esphome:
  name: hydroponic-camera
  friendly_name: Hydroponic Camera

esp32:
  board: esp32cam
  framework:
    type: arduino

# --- Сеть и базовые настройки ---
wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"

  # Точка доступа для первоначальной настройки
  # Устройство создаст эту сеть, если не сможет подключиться к основной
  ap:
    ssid: "Hydroponics Camera Setup"
    password: "password123"

# Веб-портал для настройки Wi-Fi
captive_portal:

# Включить API для интеграции с Home Assistant
api:

# Включить возможность обновления "по воздуху"
ota:

# Включить логирование
logger:

# --- Настройки камеры ---
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Настройки изображения
  name: "Вид на растения"
  resolution: 640x480
