# ===========================================
# КОНФИГУРАЦИЯ ГИДРОПОННОЙ СИСТЕМЫ
# M5Stack Atom Echo + 2-канальное реле 12В
# ===========================================
#
# ПОДКЛЮЧЕНИЕ РЕЛЕ (пример через GROVE/внешние пины):
# - Канал 1 (Освещение): IN1 -> GPIO22, VCC -> 5V, GND -> GND
# - Канал 2 (Помпа): IN2 -> GPIO23, VCC -> 5V, GND -> GND
# Примечание: При необходимости скорректируйте GPIO под вашу распайку Atom Echo.

esphome:
  name: hydroponic-tower-atom-echo
  friendly_name: Hydroponic Tower (Atom Echo)

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: recommended

# --- Сеть и базовые настройки ---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Hydroponics Atom Echo Setup"
    password: "password123"

captive_portal:

api:

ota:

logger:
  baud_rate: 115200
  level: DEBUG

# --- Веб-интерфейс ---
web_server:
  port: 80

# --- Сенсоры (опционально, пока не подключены) ---

# --- Исполнительные устройства ---
switch:
  # Канал 1 реле - управление освещением
  - platform: gpio
    pin: GPIO22
    name: "Lighting"
    id: lighting_relay
    icon: "mdi:lightbulb"

  # Канал 2 реле - управление водяной помпой
  - platform: gpio
    pin: GPIO23
    name: "Water pump"
    id: water_pump_relay
    icon: "mdi:water-pump"

# --- Автоматизация (пример, по умолчанию отключено) ---
# automation:
#   - id: "pump_schedule"
#     alias: "Water pump schedule"
#     trigger:
#       - platform: time_pattern
#         minutes: "/15"
#     action:
#       - switch.turn_on: water_pump_relay
#       - delay: 1min
#       - switch.turn_off: water_pump_relay